nome  = input("digite seu nome: ")
cpf = input("digite seu cpf: ")
dt_ nascimento = input("digite sua dt_nascimento")
cpf = int(cpf)
print(type(cpf))
dt_nascimento = int(dt_nascimento)
print(type(dt_nascimento))
print ("seu nome é: ", nome)
print ("seu cpf é: ", cpf)
print ("sua dt_nascimento", dt_nascimento)